type: "complex-bot"
integrationType: "circleci"
enabled: false # disabled because the API is considered unstable/inoperable. Use at your own risk!
name: "CircleCI"
about: "Sends CircleCI build results into the room"
avatar: "img/avatars/circleci.png"
upstream:
  type: "vector"
