type: "bot"
enabled: true
userId: "@dimension:t2bot.io"
name: "Demo Bot"
about: "A bot that has no functionality. This is just a demonstration on the config."
avatar: "/img/avatars/demobot.png"
hosted:
  homeserverUrl: "https://t2bot.io"
  accessToken: "your_matrix_access_token_here"
