# All this configuration does is make "Etherpad Widget" available in the UI
type: "widget"
integrationType: "etherpad"
enabled: true
name: "Etherpad"
about: "Collaborate on documents with members of your room."
avatar: "img/avatars/etherpad.png"

# This is the URL people will be provided when adding a new Etherpad widget. The supported variables
# are $roomId and $padName. Both will end up being URL encoded.
defaultUrl: "https://demo.riot.im/etherpad/p/$roomId_$padName"