# All this configuration does is make "Etherpad Widget" available in the UI
type: "widget"
integrationType: "etherpad"
enabled: true
name: "Etherpad"
about: "Etherpad is a collaborative text editor. With this widget you can embed Etherpad directly in to your Matrix chat rooms so that you can securely collaborate on documents."
avatar: "img/avatars/etherpad.png"
