type: "bot"
integrationType: "giphy"
enabled: true
userId: "@neb_giphy:matrix.org"
name: "Giphy"
about: "Use `!giphy query` to find an animated GIF on demand"
avatar: "img/avatars/giphy.png"

# This integration can be hosted in one of two ways: self-hosted or using vector.im's version.
# By default, vector.im's version is used, but you can host your own by uncommenting the `hosted`
# section below. Be sure to comment out or remove the `upstream` section below if you're self-hosting.
# Self-hosted bots are expected to auto-respond to invites.

upstream:
  type: "vector"
  id: "giphy"
#hosted:
#  homeserverUrl: "https://t2bot.io"
#  accessToken: "your_matrix_access_token_here"
