type: "bot"
integrationType: "guggy"
enabled: true
userId: "@_neb_guggy:matrix.org"
name: "Guggy"
about: "Use `!guggy sentence` to create an animated GIF from a sentence"
avatar: "img/avatars/guggy.png"

# This integration can be hosted in one of two ways: self-hosted or using vector.im's version.
# By default, vector.im's version is used, but you can host your own by uncommenting the `hosted`
# section below. Be sure to comment out or remove the `upstream` section below if you're self-hosting.

upstream:
  type: "vector"
  id: "guggy"
#hosted:
#  homeserverUrl: "https://t2bot.io"
#  accessToken: "your_matrix_access_token_here"
