type: "bridge"
integrationType: "irc"
enabled: true
name: "IRC"
about: "Bridges an IRC channel to the room"
avatar: "/img/avatars/irc.png"
requirements:
  joinRule: 'public'
upstream:
  type: "vector"