type: "bot"
integrationType: "wikipedia"
enabled: true
userId: "@_neb_wikipedia:matrix.org"
name: "Wikipedia"
about: "Use `!wikipedia query` to find something from Wikipedia"
avatar: "img/avatars/wikipedia.png"

# This integration can be hosted in one of two ways: self-hosted or using vector.im's version.
# By default, vector.im's version is used, but you can host your own by uncommenting the `hosted`
# section below. Be sure to comment out or remove the `upstream` section below if you're self-hosting.

upstream:
  type: "vector"
  id: "wikipedia"
#hosted:
#  homeserverUrl: "https://t2bot.io"
#  accessToken: "your_matrix_access_token_here"
