# All this configuration does is make "Youtube Widget" available in the UI
type: "widget"
integrationType: "youtube"
enabled: true
name: "YouTube Video"
about: "Embed a YouTube, Vimeo, or DailyMotion video"
avatar: "img/avatars/youtube.png"
