# The web settings for the service (API and UI)
web:
  # The port to run the webserver on
  port: 8184

  # The address to bind to (0.0.0.0 for all interfaces)
  address: '0.0.0.0'

# Settings for controlling how logging works
logging:
  file: logs/dimension.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5