# The web settings for the service (API and UI)
web:
  port: 8184
  address: '0.0.0.0'

# Settings for controlling how logging works
logging:
  file: logs/dimension.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5

# Demo bot configuration. Used purely to show how to configure a self-hosted bot in Dimension
demobot:
  enabled: false
  userId: "@dimension:t2bot.io"
  homeserverUrl: "https://t2bot.io"
  accessToken: "something"

# Upstream configuration. This should almost never change.
upstreams:
- name: vector
  url: "https://scalar.vector.im/api"

# IPs and CIDR ranges listed here will be blocked from being widgets.
# Note: Widgets may still be embedded with restricted content, although not through Dimension directly.
widgetBlacklist:
- 10.0.0.0/8
- 172.16.0.0/12
- 192.168.0.0/16
- 127.0.0.0/8