# The web settings for the service (API and UI).
# It is best to have this run on localhost and use a reverse proxy to access Dimension.
web:
  port: 8184
  address: '0.0.0.0'

# Homeserver configuration
homeserver:
  # The domain name of the homeserver. This is used in many places, such as with go-neb
  # setups, to identify the homeserver.
  name: "t2bot.io"

  # The URL that Dimension, go-neb, and other services provisioned by Dimension should
  # use to access the homeserver with.
  clientServerUrl: "https://t2bot.io"

  # The URL that Dimension should use when trying to communicate with federated APIs on
  # the homeserver. If not supplied or left empty Dimension will try to resolve the address
  # through the normal federation process.
  #federationUrl: "https://t2bot.io:8448"

  # The access token Dimension should use for miscellaneous access to the homeserver. This
  # should be for a valid user.
  accessToken: "something"

# These users can modify the integrations this Dimension supports.
# To access the admin interface, open Dimension in Riot and click the settings icon.
admins:
  - "@someone:domain.com"

# IPs and CIDR ranges listed here will be blocked from being widgets.
# Note: Widgets may still be embedded with restricted content, although not through Dimension directly.
widgetBlacklist:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 127.0.0.0/8

# Where the database for Dimension is
database:
  file: "dimension.db"

# Settings for controlling how logging works
logging:
  file: logs/dimension.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5